block_labels = [ "S-blocked" ]
delete_merged_branches = true
timeout_sec = 1200
# keep MSRV in sync in ci.yaml, bors.toml, Cargo.toml
status = [
  "style",
  "compile (stable)",
  "compile (1.63.0)",
  "doc",
  "HITL Run Status"
]
