[package]
name = "dsp"
version = "0.1.0"
authors = ["Robert JÃ¶rdens <rj@quartiq.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
