[package]
name = "dsp"
version = "0.1.0"
authors = ["Robert JÃ¶rdens <rj@quartiq.de>"]
edition = "2018"

[dependencies]
libm = "0.2.1"
serde = { version = "1.0", features = ["derive"], default-features = false }

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
ndarray = "0.14"
ndarray-stats = "0.4"

[[bench]]
name = "micro"
harness = false

[features]
nightly = []
